FROM python:3.11

WORKDIR /app/backend/WebSocket

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "FASTAPI_route:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]