from datetime import datetime, time
from schemas.user import Role
from schemas.review import ReportType

import bcrypt

salt = bcrypt.gensalt()
common_password = bcrypt.hashpw("123123123".encode("utf-8"), salt=salt)

DATABASE_SEED_DATA = {
    # ---------- Users ---------- #
    "users": [
        # ---------- Admin ---------- #
        {
            "userID": 1,
            "name": "Admin Jane",
            "emailAddress": "admin1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.ADMIN,
            "isGoogleUser": False,
        },
        {
            "userID": 12,
            "name": "Doggo",
            "emailAddress": "admin2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.ADMIN,
            "isGoogleUser": False,
        },
        # ---------- Consumer ---------- #
        {
            "userID": 2,
            "name": "Janice",
            "emailAddress": "consumer1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
            "isGoogleUser": False,
        },
        {
            "userID": 3,
            "name": "Alicia",
            "emailAddress": "consumer2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
            "isGoogleUser": False,
        },
        {
            "userID": 4,
            "name": "James",
            "emailAddress": "consumer3@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
            "isGoogleUser": False,
        },
        # ---------- Hawker ---------- #
        {
            "userID": 5,
            "name": "Alex",
            "emailAddress": "hawker1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
            "isGoogleUser": False,
        },
        {
            "userID": 6,
            "name": "Adam",
            "emailAddress": "hawker2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
            "isGoogleUser": False,
        },
        {
            "userID": 7,
            "name": "Aaron",
            "emailAddress": "hawker3@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
            "isGoogleUser": False,
        },
        {
            "userID": 8,
            "name": "William",
            "emailAddress": "hawker4@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
            "isGoogleUser": False,
        },
        {
            "userID": 9,
            "name": "Ness",
            "emailAddress": "hawker5@gmail.com",
            "password": common_password,
            "profilePhoto": "http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
            "isGoogleUser": False,
        },
    ],
    # ---------- Admin ---------- #
    "admins": [
        {
            "adminID": 1,
            "userID": 1,
        },
        {
            "adminID": 12,
            "userID": 12,
        },
    ],
    # ---------- Consumer ---------- #
    "consumers": [
        {
            "consumerID": 2,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Vegetarian",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            # "favoriteStalls": "1, 2",
            "userID": 2,
        },
        {
            "consumerID": 3,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Normal",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            # "favoriteStalls": "1, 2",
            "userID": 3,
        },
        {
            "consumerID": 4,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Normal",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            # "favoriteStalls": "1, 2",
            "userID": 4,
        },
    ],
    # ---------- Hawker ---------- #
    "hawkers": [
        {
            "hawkerID": 5,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 5,
        },
        {
            "hawkerID": 6,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 6,
        },
        {
            "hawkerID": 7,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 7,
        },
        {
            "hawkerID": 8,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 8,
        },
        {
            "hawkerID": 9,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": False,
            "userID": 9,
        },
    ],
    # ---------- Hawker Center ---------- #
    "hawkerCenters": [
        {
            "hawkerCenterID": 1,
            "name": "Marsiling Mall Hawker Centre",
            "address": "Blk 4,Woodlands St 12,Singapore�738623",
            "latitude": 1.433538857,
            "longitude": 103.7797849,
        },
        {
            "hawkerCenterID": 2,
            "name": "Bedok North Street 3 Blk 538",
            "address": "Blk 538, Bedok North Street 3, Singapore 460538",
            "latitude": 1.331781251,
            "longitude": 103.9248442,
        },
        {
            "hawkerCenterID": 3,
            "name": "Bedok North Street 4 Blk 85 (85 Fengshan Centre)",
            "address": "Blk 85, Bedok North Street 4, Singapore 460085",
            "latitude": 1.331987069,
            "longitude": 103.9387326,
        },
        {
            "hawkerCenterID": 4,
            "name": "Adam Road Food Centre",
            "address": "2, Adam Road, Singapore 289876",
            "latitude": 1.324134223,
            "longitude": 103.814165,
        },
        {
            "hawkerCenterID": 5,
            "name": "Aljunied Ave 2 Blk 117 (Blk 117 Aljunied Market and Food Centre)",
            "address": "Blk 117, Aljunied Ave 2, Singapore 380117",
            "latitude": 1.320648292,
            "longitude": 103.887019,
        },
        {
            "hawkerCenterID": 6,
            "name": "Amoy Street Food Centre (Telok Ayer Food Centre)",
            "address": "National Development Building, Annex B, Telok Ayer Street, Singapore 069111",
            "latitude": 1.279218443,
            "longitude": 103.8466068,
        },
        {
            "hawkerCenterID": 7,
            "name": "Ang Mo Kio Ave 1 Blk 226D (Kebun Baru Market and Food Centre)",
            "address": "Blk 226D, Ang Mo Kio Ave 1, Singapore 564226",
            "latitude": 1.366787645,
            "longitude": 103.8392313,
        },
        {
            "hawkerCenterID": 8,
            "name": "Ang Mo Kio Ave 1 Blk 341 (Teck Ghee Court)",
            "address": "Blk 341, Ang Mo Kio Ave 1, Singapore 560341",
            "latitude": 1.364105171,
            "longitude": 103.8482542,
        },
        {
            "hawkerCenterID": 9,
            "name": "Ang Mo Kio Ave 10 Blk 409 (Teck Ghee Square)",
            "address": "Blk 409, Ang Mo Kio Ave 10, Singapore 560409",
            "latitude": 1.362768918,
            "longitude": 103.8553698,
        },
        {
            "hawkerCenterID": 10,
            "name": "Ang Mo Kio Ave 10 Blk 453A (Chong Boon Market and Food Centre)",
            "address": "Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",
            "latitude": 1.368240493,
            "longitude": 103.8563514,
        },
        {
            "hawkerCenterID": 11,
            "name": "Ang Mo Kio Ave 10 Blk 527 (Cheng San Market and Cooked Food Centre)",
            "address": "Blk 527, Ang Mo Kio Ave 10, Singapore 560527",
            "latitude": 1.372769928,
            "longitude": 103.8544828,
        },
        {
            "hawkerCenterID": 12,
            "name": "Ang Mo Kio Ave 4 Blk 160/162 (Mayflower Market)",
            "address": "Blk 160/162, Ang Mo Kio Ave 4, Singapore 560160/560162",
            "latitude": 1.374489121,
            "longitude": 103.8392143,
        },
        {
            "hawkerCenterID": 13,
            "name": "Ang Mo Kio Ave 4 Blk 628 (Ang Mo Kio 628 Market)",
            "address": "Blk 628, Ang Mo Kio Ave 4, Singapore 560628",
            "latitude": 1.381024867,
            "longitude": 103.8406823,
        },
        {
            "hawkerCenterID": 14,
            "name": "Ang Mo Kio Ave 6 Blk 724 (Blk 724 Ang Mo Kio Market)",
            "address": "Blk 724, Ang Mo Kio Ave 6, Singapore 560724",
            "latitude": 1.372197433,
            "longitude": 103.8465192,
        },
        {
            "hawkerCenterID": 15,
            "name": "Ang Mo Kio Street 22 Blk 226H (Kebun Baru Food Centre)",
            "address": "Blk 226H, Ang Mo Kio Street 22, Singapore 568226",
            "latitude": 1.367230149,
            "longitude": 103.8399532,
        },
        {
            "hawkerCenterID": 16,
            "name": "Bedok Food Centre",
            "address": "1, Bedok Road, Singapore 469572",
            "latitude": 1.320356008,
            "longitude": 103.9554742,
        },
        {
            "hawkerCenterID": 17,
            "name": "Bedok North Street 1 Blk 216",
            "address": "Blk 216, Bedok North Street 1, Singapore 460216",
            "latitude": 1.327062409,
            "longitude": 103.9332215,
        },
        {
            "hawkerCenterID": 18,
            "name": "Bedok North Street 3 Blk 511 (Kaki Bukit 511 Market and Food Centre)",
            "address": "Blk 511, Bedok North Street 3, Singapore 460511",
            "latitude": 1.333246279,
            "longitude": 103.9306021,
        },
        {
            "hawkerCenterID": 19,
            "name": "Bedok Reservoir Road Blk 630",
            "address": "Blk 630, Bedok Reservoir Road, Singapore 470630",
            "latitude": 1.333159248,
            "longitude": 103.9140539,
        },
        {
            "hawkerCenterID": 20,
            "name": "Bedok South Road Blk 16",
            "address": "Blk 16, Bedok South Road, Singapore 460016",
            "latitude": 1.320552165,
            "longitude": 103.9355391,
        },
        {
            "hawkerCenterID": 21,
            "name": "Bendemeer Road Blk 29 (Bendemeer Market and Food Centre)",
            "address": "Blk 29, Bendemeer Road, Singapore 330029",
            "latitude": 1.319216998,
            "longitude": 103.8630214,
        },
        {
            "hawkerCenterID": 22,
            "name": "Beo Crescent Market",
            "address": "38A, Beo Crescent, Singapore 169982",
            "latitude": 1.288822102,
            "longitude": 103.827358,
        },
        {
            "hawkerCenterID": 23,
            "name": "Berseh Food Centre",
            "address": "166, Jalan Besar, Singapore 208877",
            "latitude": 1.307336517,
            "longitude": 103.856854,
        },
        {
            "hawkerCenterID": 24,
            "name": "Boon Lay Place Blk 221A/B (Boon Lay Place Market and Food Village)",
            "address": "Blk 221A/B, Boon Lay Place, Singapore 641221/642221",
            "latitude": 1.345223163,
            "longitude": 103.7127998,
        },
        {
            "hawkerCenterID": 25,
            "name": "Buffalo Road Blk 665 (Tekka Centre/Zhu Jiao Market)",
            "address": "Blk 665, Buffalo Road, Singapore 210665",
            "latitude": 1.306205841,
            "longitude": 103.850531,
        },
        {
            "hawkerCenterID": 26,
            "name": "Bukit Merah Central Blk 163 (Bukit Merah Central Food Centre)",
            "address": "Blk 163, Bukit Merah Central, Singapore 150163",
            "latitude": 1.283692589,
            "longitude": 103.8169924,
        },
        {
            "hawkerCenterID": 27,
            "name": "Bukit Merah Lane 1 Blk 120 (Alexandra Village Food Centre)",
            "address": "Blk 120, Bukit Merah Lane, Singapore 150120",
            "latitude": 1.286297772,
            "longitude": 103.8044893,
        },
        {
            "hawkerCenterID": 28,
            "name": "Bukit Merah View Blk 115 (Blk 115 Bukit Merah View Market and Food Centre)",
            "address": "Blk 115, Bukit Merah View, Singapore 151115",
            "latitude": 1.285504783,
            "longitude": 103.8220494,
        },
        {
            "hawkerCenterID": 29,
            "name": "Bukit Panjang Hawker Centre",
            "address": "2 Bukit Panjang Ring Road, Singapore 679947",
            "latitude": 1.377600535,
            "longitude": 103.7724896,
        },
        {
            "hawkerCenterID": 30,
            "name": "Bukit Timah Market",
            "address": "51, Upper Bukit Timah Road, Singapore 588215",
            "latitude": 1.339375964,
            "longitude": 103.775995,
        },
        {
            "hawkerCenterID": 31,
            "name": "Cambridge Road Blk 41A (Pek Kio Market and Food Centre)",
            "address": "Blk 41A, Cambridge Road, Singapore 211041",
            "latitude": 1.316159914,
            "longitude": 103.8502251,
        },
        {
            "hawkerCenterID": 32,
            "name": "Changi Village Blk 2 and 3",
            "address": "Blk 2/3, Changi Village Road, Singapore 500002/500003",
            "latitude": 1.389151721,
            "longitude": 103.9882457,
        },
        {
            "hawkerCenterID": 33,
            "name": "Chomp Chomp Food Centre",
            "address": "20, Kensington Park Road, Singapore 557269",
            "latitude": 1.364228523,
            "longitude": 103.8665361,
        },
        {
            "hawkerCenterID": 34,
            "name": "Ci Yuan Hawker Centre",
            "address": "51 Hougang Avenue 9, Singapore 538776",
            "latitude": 1.375428967,
            "longitude": 103.882978,
        },
        {
            "hawkerCenterID": 35,
            "name": "Circuit Road Blk 79/79A",
            "address": "Blk 79/79A, Circuit Road, Singapore 370079/371079",
            "latitude": 1.326449922,
            "longitude": 103.8850435,
        },
        {
            "hawkerCenterID": 36,
            "name": "Circuit Road Blk 80 (80 Circuit Road Market and Food Centre)",
            "address": "Blk 80, Circuit Road, Singapore 370080",
            "latitude": 1.327849561,
            "longitude": 103.8871285,
        },
        {
            "hawkerCenterID": 37,
            "name": "Circuit Road Blk 89",
            "address": "Blk 89, Circuit Road, Singapore 370089",
            "latitude": 1.323445253,
            "longitude": 103.8854492,
        },
        {
            "hawkerCenterID": 38,
            "name": "Clementi Ave 2 Blk 353 (Clementi Ave 2 Market/Cooked Food Centre)",
            "address": "Blk 353, Clementi Ave 2, Singapore 120353",
            "latitude": 1.314367728,
            "longitude": 103.7708367,
        },
        {
            "hawkerCenterID": 39,
            "name": "Clementi Ave 3 Blk 448",
            "address": "Blk 448, Clementi Ave 3, Singapore 120448",
            "latitude": 1.31326487,
            "longitude": 103.7645105,
        },
        {
            "hawkerCenterID": 40,
            "name": "Clementi West Street 2 Blk 726",
            "address": "Blk 726, Clementi West Street 2, Singapore 120726",
            "latitude": 1.303781973,
            "longitude": 103.7642644,
        },
        {
            "hawkerCenterID": 41,
            "name": "Commonwealth Crescent Market",
            "address": "31, Commonwealth Crescent, Singapore 149644",
            "latitude": 1.306892276,
            "longitude": 103.8003628,
        },
        {
            "hawkerCenterID": 42,
            "name": "Commonwealth Drive Blk 1A/2A/3A (Tanglin Halt Food Centre/Commonwealth Drive Food Centre)",
            "address": "Blk 1A/ 2A/ 3A, Commonwealth Drive, Singapore 140001/140002/140003",
            "latitude": 1.299713305,
            "longitude": 103.7978755,
        },
        {
            "hawkerCenterID": 43,
            "name": "Dunman Food Centre",
            "address": "271, Onan Road, Singapore 424768",
            "latitude": 1.309414187,
            "longitude": 103.9018251,
        },
        {
            "hawkerCenterID": 44,
            "name": "East Coast Lagoon Food Village",
            "address": "1220, East Coast Parkway, Singapore 468960",
            "latitude": 1.306684318,
            "longitude": 103.9350167,
        },
        {
            "hawkerCenterID": 45,
            "name": "Empress Road Blk 7 (Empress Road Market and Food Centre)",
            "address": "Blk 7, Empress Road, Singapore 260007",
            "latitude": 1.316245731,
            "longitude": 103.8056364,
        },
        {
            "hawkerCenterID": 46,
            "name": "Geylang Bahru Blk 69 (Blk 69 Geylang Bahru Market and Food Centre)",
            "address": "Blk 69, Geylang Bahru, Singapore 330069",
            "latitude": 1.32146226,
            "longitude": 103.8700044,
        },
        {
            "hawkerCenterID": 47,
            "name": "Geylang Serai Market",
            "address": "1, Geylang Serai, Singapore 402001",
            "latitude": 1.316728148,
            "longitude": 103.8982243,
        },
        {
            "hawkerCenterID": 48,
            "name": "Ghim Moh Road Blk 20",
            "address": "Blk 20, Ghim Moh Road, Singapore 270020",
            "latitude": 1.310996273,
            "longitude": 103.7882307,
        },
        {
            "hawkerCenterID": 49,
            "name": "Golden Mile Food Centre",
            "address": "505, Beach Road, Singapore 199583",
            "latitude": 1.302875481,
            "longitude": 103.8638832,
        },
        {
            "hawkerCenterID": 50,
            "name": "Haig Road Blk 13/14 (Haig Road Market and Cooked Food Centre)",
            "address": "Blk 13/14, Haig Road, Singapore 430013/430014",
            "latitude": 1.315142051,
            "longitude": 103.8956095,
        },
        {
            "hawkerCenterID": 51,
            "name": "Havelock Road Blk 22A/B (Havelock Road Cooked Food Centre)",
            "address": "Blk 22A/B, Havelock Road, Singapore 161022/162022",
            "latitude": 1.28797544,
            "longitude": 103.8296268,
        },
        {
            "hawkerCenterID": 52,
            "name": "Hawker Centre @ Our Tampines Hub",
            "address": "1 Tampines Walk, Singapore 528523",
            "latitude": 1.353862118,
            "longitude": 103.9397262,
        },
        {
            "hawkerCenterID": 53,
            "name": "Shunfu Road Blk 320 (Shunfu Mart)",
            "address": "Blk 320, Shunfu Road, Singapore 570320",
            "latitude": 1.352007442,
            "longitude": 103.8370318,
        },
        {
            "hawkerCenterID": 54,
            "name": "Sims Place Blk 49 (Sims Vista Market and Food Centre)",
            "address": "Blk 49, Sims Place, Singapore 380049",
            "latitude": 1.317083351,
            "longitude": 103.879417,
        },
        {
            "hawkerCenterID": 55,
            "name": "Smith Street Blk 335 (Chinatown Complex Market)",
            "address": "Blk 335, Smith Street, Singapore 050335",
            "latitude": 1.282235148,
            "longitude": 103.8431776,
        },
        {
            "hawkerCenterID": 56,
            "name": "Taman Jurong Market and Food Centre",
            "address": "3, Yung Sheng Road, Singapore 618499",
            "latitude": 1.33458936,
            "longitude": 103.7215199,
        },
        {
            "hawkerCenterID": 57,
            "name": "Tampines Street 11 Blk 137 (Tampines Round Market and Food Centre)",
            "address": "Blk 137, Tampines Street 11, Singapore 521137",
            "latitude": 1.345639521,
            "longitude": 103.9446245,
        },
        {
            "hawkerCenterID": 58,
            "name": "Tanglin Halt Market",
            "address": "48A, Tanglin Halt Road, Singapore 148813",
            "latitude": 1.300789315,
            "longitude": 103.7976258,
        },
        {
            "hawkerCenterID": 59,
            "name": "Tanjong Pagar Plaza Blk 6 (Blk 6 Tanjong Pagar Plaza Market and Food Centre)",
            "address": "Blk 6, Tanjong Pagar Plaza, Singapore 081006",
            "latitude": 1.276614611,
            "longitude": 103.843167,
        },
        {
            "hawkerCenterID": 60,
            "name": "Teban Gardens Road Blk 37A (Teban Gardens Market and Food Centre)",
            "address": "Blk 37A, Teban Garden Road, Singapore 601037",
            "latitude": 1.32084835,
            "longitude": 103.7428916,
        },
        {
            "hawkerCenterID": 61,
            "name": "Telok Blangah Crescent Blk 11 (11 Telok Blangah Crescent Market and Food Centre)",
            "address": "Blk 11, Telok Blangah Crescent, Singapore 090011",
            "latitude": 1.277366838,
            "longitude": 103.8186417,
        },
        {
            "hawkerCenterID": 62,
            "name": "Eunos Crescent Blk 4A",
            "address": "Blk 4A, Eunos Crescent, Singapore 402004",
            "latitude": 1.320331782,
            "longitude": 103.9042609,
        },
        {
            "hawkerCenterID": 63,
            "name": "Telok Blangah Drive Blk 79 (Telok Blangah Food Centre)",
            "address": "Blk 79, Telok Blangah Drive, Singapore 100079",
            "latitude": 1.273368283,
            "longitude": 103.8076268,
        },
        {
            "hawkerCenterID": 64,
            "name": "Zion Riverside Food Centre",
            "address": "70, Zion Road, Singapore 247792",
            "latitude": 1.292342168,
            "longitude": 103.8311893,
        },
        {
            "hawkerCenterID": 65,
            "name": "Holland Drive Blk 44 (Holland Drive Market and Food Centre)",
            "address": "Blk 44, Holland Drive, Singapore 270044",
            "latitude": 1.308117759,
            "longitude": 103.7927738,
        },
        {
            "hawkerCenterID": 66,
            "name": "Holland Village Market and Food Centre",
            "address": "1, Lorong Mambong, Singapore 277700",
            "latitude": 1.310908028,
            "longitude": 103.7948629,
        },
        {
            "hawkerCenterID": 67,
            "name": "Hougang Ave 1 Blk 105 (Hougang 105 Hainanese Village Centre)",
            "address": "Blk 105, Hougang Ave 1, Singapore 530105",
            "latitude": 1.353837391,
            "longitude": 103.8900811,
        },
        {
            "hawkerCenterID": 68,
            "name": "Hougang Street 21 Blk 209 (Kovan Hougang Market and Food Centre)",
            "address": "Blk 209, Hougang Street 21, Singapore 530209",
            "latitude": 1.359119422,
            "longitude": 103.8859776,
        },
        {
            "hawkerCenterID": 69,
            "name": "Jalan Batu Blk 4A (Blk 4A Jalan Batu Hawker Centre/Market)",
            "address": "Blk 4A, Jalan Batu, Singapore 432004",
            "latitude": 1.302418814,
            "longitude": 103.8839406,
        },
        {
            "hawkerCenterID": 70,
            "name": "Jalan Bukit Merah Blk 112 (Blk 112 Jalan Bukit Merah Market and Food Centre)",
            "address": "Blk 112, Jalan Bukit Merah, Singapore 160112",
            "latitude": 1.280004812,
            "longitude": 103.8260133,
        },
        {
            "hawkerCenterID": 71,
            "name": "Jalan Bukit Merah Blk 6 (ABC Brickworks Market/Food Centre)",
            "address": "Blk 6, Jalan Bukit Merah, Singapore 150006",
            "latitude": 1.286952752,
            "longitude": 103.808128,
        },
        {
            "hawkerCenterID": 72,
            "name": "Jalan Kukoh Blk 1 (Kukoh 21 Food Centre)",
            "address": "Blk 1, Jalan Kukoh, Singapore 161001",
            "latitude": 1.288230555,
            "longitude": 103.8399459,
        },
        {
            "hawkerCenterID": 73,
            "name": "Jurong East Ave 1 Blk 347 (Yuhua Market and Hawker Centre)",
            "address": "Blk 347, Jurong East Ave 1, Singapore 600347",
            "latitude": 1.34531247,
            "longitude": 103.7315797,
        },
        {
            "hawkerCenterID": 74,
            "name": "Jurong East Street 24 Blk 254 (Yuhua Village Market and Food Centre)",
            "address": "Blk 254, Jurong East Street 24, Singapore 600254",
            "latitude": 1.343442138,
            "longitude": 103.7377812,
        },
        {
            "hawkerCenterID": 75,
            "name": "Jurong West Hawker Centre",
            "address": "Blk 50, Jurong West St 61, Singapore 648202",
            "latitude": 1.341259706,
            "longitude": 103.6974043,
        },
        {
            "hawkerCenterID": 76,
            "name": "Jurong West Street 52 Blk 505",
            "address": "Blk 505, Jurong West Street 52, Singapore 640505",
            "latitude": 1.349642243,
            "longitude": 103.7184475,
        },
        {
            "hawkerCenterID": 77,
            "name": "Kallang Estate Fresh Market and Food Centre",
            "address": "17, Old Airport Road, Singapore 397972",
            "latitude": 1.30739616,
            "longitude": 103.8841302,
        },
        {
            "hawkerCenterID": 78,
            "name": "Redhill Lane Blk 85 (Redhill Food Centre)",
            "address": "Blk 85, Redhill Lane, Singapore 150085",
            "latitude": 1.287330767,
            "longitude": 103.8183389,
        },
        {
            "hawkerCenterID": 79,
            "name": "Kampung Admiralty Hawker Centre",
            "address": "Blk 676, Woodlands Drive 71, Singapore 730676",
            "latitude": 1.439932832,
            "longitude": 103.8006964,
        },
        {
            "hawkerCenterID": 80,
            "name": "Marine Parade Central Blk 84 (84 Marine Parade Central Market and Food Centre)",
            "address": "Blk 84, Marine Parade Central, Singapore 440084",
            "latitude": 1.302285138,
            "longitude": 103.9063385,
        },
        {
            "hawkerCenterID": 81,
            "name": "Marine Terrace Blk 50A (50A Marine Terrace)",
            "address": "Blk 50A, Marine Terrace, Singapore 441050",
            "latitude": 1.305775148,
            "longitude": 103.915762,
        },
        {
            "hawkerCenterID": 82,
            "name": "Marsiling Lane Blk 20/21",
            "address": "Blk 20/21, Marsiling Lane, Singapore 730020/730021",
            "latitude": 1.443881817,
            "longitude": 103.7772032,
        },
        {
            "hawkerCenterID": 83,
            "name": "Maxwell Food Centre (Kim Hua Market)",
            "address": "1, Kadayanallur Street, Singapore 069184",
            "latitude": 1.280112235,
            "longitude": 103.8448279,
        },
        {
            "hawkerCenterID": 84,
            "name": "Mei Chin Road Blk 159 (Mei Chin Road Market)",
            "address": "Blk 159, Mei Chin Road, Singapore 140159",
            "latitude": 1.293236221,
            "longitude": 103.8029039,
        },
        {
            "hawkerCenterID": 85,
            "name": "New Market Road Blk 32 (People's Park Food Centre)",
            "address": "Blk 32, New Market Road, Singapore 050032",
            "latitude": 1.284991022,
            "longitude": 103.8425788,
        },
        {
            "hawkerCenterID": 86,
            "name": "New Upper Changi Road Blk 208B",
            "address": "Blk 208B, New Upper Changi Road, Singapore 462208",
            "latitude": 1.324738845,
            "longitude": 103.9305605,
        },
        {
            "hawkerCenterID": 87,
            "name": "New Upper Changi Road Blk 58",
            "address": "Blk 58, New Upper Changi Road, Singapore 461058",
            "latitude": 1.324187828,
            "longitude": 103.9411324,
        },
        {
            "hawkerCenterID": 88,
            "name": "Newton Food Centre",
            "address": "500, Clemenceau Ave North, Singapore 229495",
            "latitude": 1.311892357,
            "longitude": 103.8395627,
        },
        {
            "hawkerCenterID": 89,
            "name": "North Bridge Road Market",
            "address": "861, North Bridge Road, Singapore 198783",
            "latitude": 1.305765378,
            "longitude": 103.863891,
        },
        {
            "hawkerCenterID": 90,
            "name": "Old Airport Road Blk 51 (51 Old Airport Road Food Centre and Shopping Mall)",
            "address": "Blk 51, Old Airport Road, Singapore 390051",
            "latitude": 1.308251563,
            "longitude": 103.8858332,
        },
        {
            "hawkerCenterID": 91,
            "name": "Pasir Panjang Food Centre",
            "address": "121, Pasir Panjang Road, Singapore 118543",
            "latitude": 1.275907525,
            "longitude": 103.7914027,
        },
        {
            "hawkerCenterID": 92,
            "name": "Pasir Ris Central Hawker Centre",
            "address": "Blk 110, Pasir Ris Central, Singapore 519641",
            "latitude": 1.37343414,
            "longitude": 103.951543,
        },
        {
            "hawkerCenterID": 93,
            "name": "Queen Street Blk 270 (Albert Centre)",
            "address": "Blk 270, Queen Street, Singapore 180270",
            "latitude": 1.301001465,
            "longitude": 103.8542116,
        },
        {
            "hawkerCenterID": 94,
            "name": "Redhill Lane Blk 79 (Redhill Market)",
            "address": "Blk 79, Redhill Lane, Singapore 150079",
            "latitude": 1.287858103,
            "longitude": 103.8184026,
        },
        {
            "hawkerCenterID": 95,
            "name": "Sembawang Hills Food Centre (Jalan Leban Food Centre)",
            "address": "590, Upper Thomson Road, Singapore 574419",
            "latitude": 1.37238494,
            "longitude": 103.8289942,
        },
        {
            "hawkerCenterID": 96,
            "name": "Serangoon Garden Market",
            "address": "49A, Serangoon Garden Way, Singapore 555945",
            "latitude": 1.36315712,
            "longitude": 103.8667375,
        },
        {
            "hawkerCenterID": 97,
            "name": "Telok Blangah Drive Blk 82 (Telok Blangah Market)",
            "address": "Blk 82, Telok Blangah Drive, Singapore 100082",
            "latitude": 1.273913799,
            "longitude": 103.8079436,
        },
        {
            "hawkerCenterID": 98,
            "name": "Telok Blangah Rise Blk 36 (Telok Blangah Rise Market)",
            "address": "Blk 36, Telok Blangah Rise, Singapore 090036",
            "latitude": 1.272715797,
            "longitude": 103.8221173,
        },
        {
            "hawkerCenterID": 99,
            "name": "Tiong Bahru Market",
            "address": "30, Seng Poh Road, Singapore 168898",
            "latitude": 1.285088258,
            "longitude": 103.8323488,
        },
        {
            "hawkerCenterID": 100,
            "name": "Toa Payoh Lorong 1 Blk 127 (Toa Payoh West Market and Food Court)",
            "address": "Blk 127, Lorong 1 Toa Payoh, Singapore 310127",
            "latitude": 1.338092686,
            "longitude": 103.8447316,
        },
        {
            "hawkerCenterID": 101,
            "name": "Toa Payoh Lorong 4 Blk 74 (Toa Payoh Vista Market)",
            "address": "Blk 74, Lorong 4 Toa Payoh, Singapore 310074",
            "latitude": 1.334548165,
            "longitude": 103.8519991,
        },
        {
            "hawkerCenterID": 102,
            "name": "Toa Payoh Lorong 4 Blk 93",
            "address": "Blk 93, Lorong 4 Toa Payoh, Singapore 310093",
            "latitude": 1.338474752,
            "longitude": 103.8495135,
        },
        {
            "hawkerCenterID": 103,
            "name": "Toa Payoh Lorong 5 Blk 75",
            "address": "Blk 75, Lorong 5 Toa Payoh, Singapore 310075",
            "latitude": 1.336038822,
            "longitude": 103.8529416,
        },
        {
            "hawkerCenterID": 104,
            "name": "Toa Payoh Lorong 7 Blk 22 (Kim Keat Palm Market and Food Centre)",
            "address": "Blk 22, Lorong 7 Toa Payoh, Singapore 310022",
            "latitude": 1.335231459,
            "longitude": 103.857036,
        },
        {
            "hawkerCenterID": 105,
            "name": "Toa Payoh Lorong 8 Blk 210",
            "address": "Blk 210, Lorong 8 Toa Payoh, Singapore 310210",
            "latitude": 1.340260835,
            "longitude": 103.8543953,
        },
        {
            "hawkerCenterID": 106,
            "name": "Upper Boon Keng Road Blk 17 (Blk 17 Upper Boon Keng Market and Food Centre)",
            "address": "Blk 17, Upper Boon Keng Road, Singapore 380017",
            "latitude": 1.315028044,
            "longitude": 103.8716203,
        },
        {
            "hawkerCenterID": 107,
            "name": "Upper Cross Street Blk 531A (Hong Lim Food Centre and Market)",
            "address": "Blk 531A, Upper Cross Street, Singapore 051531",
            "latitude": 1.2852464,
            "longitude": 103.8458189,
        },
        {
            "hawkerCenterID": 108,
            "name": "West Coast Drive Blk 502 (Ayer Rajah Market)",
            "address": "Blk 502, West Coast Drive, Singapore 120502",
            "latitude": 1.311889721,
            "longitude": 103.7591661,
        },
        {
            "hawkerCenterID": 109,
            "name": "West Coast Drive Blk 503 (Ayer Rajah Food Centre)",
            "address": "Blk 503, West Coast Drive, Singapore 120503",
            "latitude": 1.31180301,
            "longitude": 103.7597513,
        },
        {
            "hawkerCenterID": 110,
            "name": "Whampoa Drive Blk 90 (Whampoa Drive Makan Place/Whampoa Food Centre)",
            "address": "Blk 90, Whampoa Drive, Singapore 320090",
            "latitude": 1.322943062,
            "longitude": 103.8551377,
        },
        {
            "hawkerCenterID": 111,
            "name": "Whampoa Drive Blk 91/92 (Whampoa Drive Makan Place/Whampoa Market)",
            "address": "Blk 91/92, Whampoa Drive, Singapore 320091/320092",
            "latitude": 1.323421751,
            "longitude": 103.8540681,
        },
        {
            "hawkerCenterID": 112,
            "name": "Yishun Park Hawker Centre",
            "address": "Blk 51, Yishun Avenue 11, Singapore 768867",
            "latitude": 1.425017638,
            "longitude": 103.8447476,
        },
        {
            "hawkerCenterID": 113,
            "name": "Yishun Ring Road Blk 104/105 (Chong Pang Market and Food Centre)",
            "address": "Blk 104/105, Yishun Ring Road, Singapore 760104/760105",
            "latitude": 1.431447688,
            "longitude": 103.8285376,
        },
    ],
    # ---------- Stall ---------- #
    "stalls": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "stallID": 1,
            "stallName": "Mala Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-01",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "A",
            "cuisineType": "Chinese, Indian",
            "estimatedWaitTime": 15,
            "priceRange": "$4 - $8",
            "hawkerID": 5,
            "hawkerCenterID": 1,
        },
        {
            "stallID": 2,
            "stallName": "Korean BBQ Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-02",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "B",
            "cuisineType": "Korean",
            "estimatedWaitTime": 20,
            "priceRange": "$4 - $8",
            "hawkerID": 5,
            "hawkerCenterID": 2,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "stallID": 3,
            "stallName": "Cai Fan Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-03",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "C",
            "cuisineType": "Chinese, Indian",
            "estimatedWaitTime": 10,
            "priceRange": "$4 - $8",
            "hawkerID": 6,
            "hawkerCenterID": 3,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "stallID": 4,
            "stallName": "Mixed Rice Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-04",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 7,
            "hawkerCenterID": 4,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "stallID": 5,
            "stallName": "Chicken Rice Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-05",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 8,
            "hawkerCenterID": 5,
        },
        # ----- For Noodles Store (stallID 9) ----- #
        {
            "stallID": 6,
            "stallName": "Noodles Store",
            "images": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://localhost:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-06",
            "startTime": time(10, 0, 0),
            "endTime": time(20, 0, 0),
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 9,
            "hawkerCenterID": 6,
        },
    ],
    # ---------- Review ---------- #
    "reviews": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "reviewID": 1,
            "reviewText": "Hot and spicy! It is very delicious!! 😋",
            "rating": 5.0,
            "isReported": True,
            "reportType": ReportType.SPAM,
            "reportText": "This review is spam",
            "consumerID": 2,
            "stallID": 1,
        },
        {
            "reviewID": 2,
            "reviewText": "Nice and cosy environment to eat mala with friends >.<",
            "rating": 5.0,
            "isReported": True,
            "reportType": ReportType.IRRELEVANT,
            "reportText": "This review is irrelevant",
            "consumerID": 3,
            "stallID": 1,
        },
        {
            "reviewID": 3,
            "reviewText": "Hate it! It was too spicy and it made me sweat in front of my interviewer 😠😠",
            "rating": 0.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 2,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "reviewID": 4,
            "reviewText": "Big portion. But on a more pricy side.",
            "rating": 3.8,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 3,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "reviewID": 5,
            "reviewText": "Cheap!",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 3,
            "stallID": 4,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "reviewID": 6,
            "reviewText": "Chicken is very tender! Highly recommended",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 2,
            "stallID": 5,
        },
        {
            "reviewID": 7,
            "reviewText": "🤮🤮🤮🤮",
            "rating": 1.5,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 6,
        },
    ],
    # ---------- Dish ---------- #
    "dishes": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "dishID": 1,
            "stallID": 1,
            "dishName": "Mala Xiang Guo",
            "price": 6.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        {
            "dishID": 2,
            "stallID": 2,
            "dishName": "Korean BBQ Set",
            "price": 10.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "dishID": 3,
            "stallID": 3,
            "dishName": "Cai Fan",
            "price": 4.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "dishID": 4,
            "stallID": 4,
            "dishName": "Mixed Rice",
            "price": 4.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "dishID": 5,
            "stallID": 5,
            "dishName": "Chicken Rice",
            "price": 3.5,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For Noodles Store (stallID 9) ----- #
        {
            "dishID": 6,
            "stallID": 6,
            "dishName": "Noodles",
            "price": 3.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": False,
        },
        {
            "dishID": 7,
            "stallID": 1,
            "dishName": "Noodles",
            "price": 3.0,
            "photo": "http://localhost:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": False,
        },
    ],
    # ---------- Promotion ---------- #
    "promotions": [
        {
            "promotionID": 1,
            "dishID": 1,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 5.0,
        },
        {
            "promotionID": 2,
            "dishID": 2,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 3,
            "dishID": 3,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 4,
            "dishID": 4,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 5,
            "dishID": 5,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 2.5,
        },
    ],
    # ---------- LikeStall ---------- #
    "like_stalls": [
        {
            "userID": 2,
            "stallID": 1,
        },
        {
            "userID": 2,
            "stallID": 2,
        },
        {
            "userID": 3,
            "stallID": 3,
        },
    ],
}
