from datetime import datetime
from schemas.user import Role

import bcrypt

salt = bcrypt.gensalt()
common_password = bcrypt.hashpw("123123123".encode("utf-8"), salt=salt)

DATABASE_SEED_DATA = {
    # ---------- Users ---------- #
    "users": [
        # ---------- Admin ---------- #
        {
            "userID": 1,
            "name": "Admin Jane",
            "emailAddress": "admin1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.ADMIN,
        },
        {
            "userID": 12,
            "name": "Doggo",
            "emailAddress": "admin2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.ADMIN,
        },
        # ---------- Consumer ---------- #
        {
            "userID": 2,
            "name": "Janice",
            "emailAddress": "consumer1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
        },
        {
            "userID": 3,
            "name": "Alicia",
            "emailAddress": "consumer2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
        },
        {
            "userID": 4,
            "name": "James",
            "emailAddress": "consumer3@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.CONSUMER,
        },
        # ---------- Hawker ---------- #
        {
            "userID": 5,
            "name": "Alex",
            "emailAddress": "hawker1@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
        },
        {
            "userID": 6,
            "name": "Adam",
            "emailAddress": "hawker2@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
        },
        {
            "userID": 7,
            "name": "Aaron",
            "emailAddress": "hawker3@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
        },
        {
            "userID": 8,
            "name": "William",
            "emailAddress": "hawker4@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
        },
        {
            "userID": 9,
            "name": "Ness",
            "emailAddress": "hawker5@gmail.com",
            "password": common_password,
            "profilePhoto": "http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "contactNumber": "95874723",
            "role": Role.HAWKER,
        },
    ],
    # ---------- Admin ---------- #
    "admins": [
        {
            "adminID": 1,
            "userID": 1,
        },
        {
            "adminID": 12,
            "userID": 12,
        },
    ],
    # ---------- Consumer ---------- #
    "consumers": [
        {
            "consumerID": 2,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Vegetarian",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            "favoriteStalls": "1, 2",
            "userID": 2,
        },
        {
            "consumerID": 3,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Normal",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            "favoriteStalls": "1, 2",
            "userID": 3,
        },
        {
            "consumerID": 4,
            "address": "Nanyang Technological University",
            "dietaryPreference": "Normal",
            "preferredCuisine": "Chinese",
            "ambulatoryStatus": "Normal",
            "favoriteStalls": "1, 2",
            "userID": 4,
        },
    ],
    # ---------- Hawker ---------- #
    "hawkers": [
        {
            "hawkerID": 5,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 5,
        },
        {
            "hawkerID": 6,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 6,
        },
        {
            "hawkerID": 7,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 7,
        },
        {
            "hawkerID": 8,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 8,
        },
        {
            "hawkerID": 9,
            "address": "Nanyang Technological University",
            "license": "123456789",
            "verifyStatus": True,
            "userID": 9,
        },
    ],
    # ---------- Hawker Center ---------- #
    "hawkerCenters": [
        {
            "hawkerCenterID": 1,
            "name": "NTU",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 1,
        },
        {
            "hawkerCenterID": 2,
            "name": "North Spine",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 2,
        },
        {
            "hawkerCenterID": 3,
            "name": "North Spine",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 3,
        },
        {
            "hawkerCenterID": 4,
            "name": "North Spine",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 4,
        },
        {
            "hawkerCenterID": 5,
            "name": "North Spine",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 5,
        },
        {
            "hawkerCenterID": 6,
            "name": "North Spine",
            "address": "Nanyang Technological University",
            "latitude": 1.35397,
            "longitude": 103.68779,
            "stallID": 6,
        },
    ],
    # ---------- Stall ---------- #
    "stalls": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "stallID": 1,
            "stallName": "Mala Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-01",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "A",
            "cuisineType": "Chinese, Indian",
            "estimatedWaitTime": 15,
            "priceRange": "$4 - $8",
            "hawkerID": 5,
            "hawkerCenterID": 1,
        },
        {
            "stallID": 2,
            "stallName": "Korean BBQ Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-02",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "B",
            "cuisineType": "Korean",
            "estimatedWaitTime": 20,
            "priceRange": "$4 - $8",
            "hawkerID": 5,
            "hawkerCenterID": 2,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "stallID": 3,
            "stallName": "Cai Fan Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-03",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "C",
            "cuisineType": "Chinese, Indian",
            "estimatedWaitTime": 10,
            "priceRange": "$4 - $8",
            "hawkerID": 6,
            "hawkerCenterID": 3,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "stallID": 4,
            "stallName": "Mixed Rice Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-04",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 7,
            "hawkerCenterID": 4,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "stallID": 5,
            "stallName": "Chicken Rice Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-05",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 8,
            "hawkerCenterID": 5,
        },
        # ----- For Noodles Store (stallID 9) ----- #
        {
            "stallID": 6,
            "stallName": "Noodles Store",
            "images": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo, http://minio:9000/profile-photo/user10_example.com_15dc5a24_profile-photo",
            "unitNumber": "01-06",
            "startTime": "10:00",
            "endTime": "20:00",
            "hygieneRating": "A",
            "cuisineType": "Chinese",
            "estimatedWaitTime": 5,
            "priceRange": "$4 - $8",
            "hawkerID": 9,
            "hawkerCenterID": 6,
        },
    ],
    # ---------- Review ---------- #
    "reviews": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "reviewID": 1,
            "reviewText": "Hot and spicy! It is very delicious!! 😋",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 2,
            "stallID": 1,
        },
        {
            "reviewID": 2,
            "reviewText": "Nice and cosy environment to eat mala with friends >.<",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 3,
            "stallID": 1,
        },
        {
            "reviewID": 3,
            "reviewText": "Hate it! It was too spicy and it made me sweat in front of my interviewer 😠😠",
            "rating": 0.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 2,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "reviewID": 4,
            "reviewText": "Big portion. But on a more pricy side.",
            "rating": 3.8,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 3,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "reviewID": 5,
            "reviewText": "Cheap!",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 3,
            "stallID": 4,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "reviewID": 6,
            "reviewText": "Chicken is very tender! Highly recommended",
            "rating": 5.0,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 2,
            "stallID": 5,
        },
        {
            "reviewID": 7,
            "reviewText": "🤮🤮🤮🤮",
            "rating": 1.5,
            "isReported": False,
            "reportType": None,
            "reportText": None,
            "consumerID": 4,
            "stallID": 6,
        },
    ],
    # ---------- Dish ---------- #
    "dishes": [
        # ----- For A Hot Hideout (hawkerID 5) ----- #
        {
            "dishID": 1,
            "stallID": 1,
            "dishName": "Mala Xiang Guo",
            "price": 6.0,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        {
            "dishID": 2,
            "stallID": 2,
            "dishName": "Korean BBQ Set",
            "price": 10.0,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For North Spine Kofu Cai Fan (stallID 6) ----- #
        {
            "dishID": 3,
            "stallID": 3,
            "dishName": "Cai Fan",
            "price": 4.0,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For The Crowded Bowl (stallID 7) ----- #
        {
            "dishID": 4,
            "stallID": 4,
            "dishName": "Mixed Rice",
            "price": 4.0,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For Chicken Rice Store (stallID 8) ----- #
        {
            "dishID": 5,
            "stallID": 5,
            "dishName": "Chicken Rice",
            "price": 3.5,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": True,
        },
        # ----- For Noodles Store (stallID 9) ----- #
        {
            "dishID": 6,
            "stallID": 6,
            "dishName": "Noodles",
            "price": 3.0,
            "photo": "http://minio:9000/profile-photo/user_example.com_55d0ae45_profile-photo",
            "onPromotion": False,
        },
    ],
    # ---------- Promotion ---------- #
    "promotions": [
        {
            "promotionID": 1,
            "dishID": 1,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 5.0,
        },
        {
            "promotionID": 2,
            "dishID": 2,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 3,
            "dishID": 3,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 4,
            "dishID": 4,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 3.0,
        },
        {
            "promotionID": 5,
            "dishID": 5,
            "startDate": datetime(2021, 1, 1),
            "endDate": datetime(2021, 12, 31),
            "discountedPrice": 2.5,
        },
    ],
}
